# Generated by Django 4.2.4 on 2024-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=105, verbose_name='Наименование')),
                ('descriptions', models.CharField(max_length=145, verbose_name='Описание')),
                ('url_link', models.URLField(blank=True, max_length=699, verbose_name='Ссылка на страницу')),
                ('image', models.ImageField(blank=True, upload_to='service/', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы для гл стр',
            },
        ),
    ]
