# Generated by Django 4.2.4 on 2024-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorm',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='serviceorm',
            name='descriptions',
            field=models.TextField(max_length=145, verbose_name='Описание'),
        ),
    ]
