# Generated by Django 4.2.4 on 2024-04-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_serviceorm_is_active_alter_serviceorm_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorm',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='serviceorm',
            name='title',
        ),
        migrations.AddField(
            model_name='serviceorm',
            name='descriptions_kg',
            field=models.TextField(default=23, max_length=145, verbose_name='Описание на кыргызском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorm',
            name='descriptions_ru',
            field=models.TextField(default=23, max_length=145, verbose_name='Описание на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorm',
            name='title_kg',
            field=models.CharField(default=23, max_length=105, verbose_name='Наименование на кыргызском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorm',
            name='title_ru',
            field=models.CharField(default=32, max_length=105, verbose_name='Наименование на русском'),
            preserve_default=False,
        ),
    ]
