# Generated by Django 4.2.4 on 2024-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=299, null=True, verbose_name='Название вакансии')),
                ('city', models.CharField(blank=True, max_length=299, null=True, verbose_name='Название отдела и города')),
                ('note', models.CharField(blank=True, max_length=299, null=True, verbose_name='Примичание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
