# Generated by Django 4.2.4 on 2024-04-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='note',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='note_kg',
            field=models.CharField(blank=True, max_length=599, null=True, verbose_name='Примичание на кыргызском'),
        ),
        migrations.AddField(
            model_name='job',
            name='note_ru',
            field=models.CharField(blank=True, max_length=599, null=True, verbose_name='Примичание на русском'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_kg',
            field=models.CharField(blank=True, max_length=299, null=True, verbose_name='Название вакансии на кыргызском'),
        ),
        migrations.AddField(
            model_name='job',
            name='title_ru',
            field=models.CharField(blank=True, max_length=299, null=True, verbose_name='Название вакансии на руссском'),
        ),
    ]
