# Generated by Django 4.2.4 on 2024-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=555, null=True, verbose_name='Наименование отдела')),
                ('address', models.CharField(blank=True, max_length=555, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=555, null=True, verbose_name='Контактные данные')),
                ('time_job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время и график работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=6999, null=True, verbose_name='История')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Биография')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Руководства',
                'verbose_name_plural': 'Руководители',
            },
        ),
    ]
