# Generated by Django 4.2.4 on 2024-04-26 10:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='description',
        ),
        migrations.AddField(
            model_name='management',
            name='description_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=12, verbose_name='Биограция на кыргызском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='management',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=12, verbose_name='Биограция на русском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, max_length=555, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time_job',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Время и график работы'),
        ),
    ]
