# Generated by Django 4.2.4 on 2024-04-26 11:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_management_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=1, verbose_name='История'),
            preserve_default=False,
        ),
    ]
