# Generated by Django 4.2.4 on 2024-05-23 05:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_history_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=555, null=True, verbose_name='Адрес'),
        ),
    ]
