# Generated by Django 4.2.4 on 2024-04-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
