# Generated by Django 4.2.4 on 2024-04-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_remove_appeal_category_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=299, verbose_name='Отдел'),
        ),
    ]
