# Generated by Django 4.2.4 on 2024-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=599, null=True, verbose_name='№')),
                ('title', models.CharField(blank=True, max_length=599, null=True, verbose_name='Наименование услуги')),
                ('price', models.CharField(blank=True, max_length=599, null=True, verbose_name='Стоимость')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Подтверждение',
                'verbose_name_plural': 'Подтверждение сведений о транспортных средствах и водительских удостоверениях',
            },
        ),
        migrations.CreateModel(
            name='Issue_Car01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=599, null=True, verbose_name='№')),
                ('title', models.CharField(blank=True, max_length=599, null=True, verbose_name='Наименование услуги')),
                ('price', models.CharField(blank=True, max_length=599, null=True, verbose_name='Стоимость')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдача водительского удостоверения на право управления транспортными средствами',
            },
        ),
        migrations.CreateModel(
            name='Issue_Car02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=599, null=True, verbose_name='№')),
                ('title', models.CharField(blank=True, max_length=599, null=True, verbose_name='Наименование услуги')),
                ('price', models.CharField(blank=True, max_length=599, null=True, verbose_name='Стоимость')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдача удостоверения тракториста машиниста на право управления самоходными технологическими машинами',
            },
        ),
        migrations.CreateModel(
            name='Register_Car01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=599, null=True, verbose_name='№')),
                ('title', models.CharField(blank=True, max_length=599, null=True, verbose_name='Наименование услуги')),
                ('price', models.CharField(blank=True, max_length=599, null=True, verbose_name='Стоимость')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация прав собственности на автотранспорт',
            },
        ),
        migrations.CreateModel(
            name='Register_Car02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=599, null=True, verbose_name='№')),
                ('title', models.CharField(blank=True, max_length=599, null=True, verbose_name='Наименование услуги')),
                ('price', models.CharField(blank=True, max_length=599, null=True, verbose_name='Стоимость')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация прав собственности на трактора и оборудование',
            },
        ),
    ]
