# Generated by Django 4.2.4 on 2024-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=255, verbose_name='Вопрос на русском')),
                ('question_kg', models.CharField(max_length=255, verbose_name='Вопрос на кыргызском')),
                ('answer_ru', models.TextField(verbose_name='Ответ на русском')),
                ('answer_kg', models.TextField(verbose_name='Ответ на кыргызском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
