# Generated by Django 4.2.4 on 2024-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_faqmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodels',
            name='question_kg',
            field=models.TextField(max_length=255, verbose_name='Вопрос на кыргызском'),
        ),
        migrations.AlterField(
            model_name='faqmodels',
            name='question_ru',
            field=models.TextField(max_length=255, verbose_name='Вопрос на русском'),
        ),
    ]
