# Generated by Django 4.2.4 on 2024-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_faqmodels_question_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModelsTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.TextField(max_length=955, verbose_name='Вопрос на русском')),
                ('question_kg', models.TextField(max_length=955, verbose_name='Вопрос на кыргызском')),
                ('answer_ru', models.TextField(verbose_name='Ответ на русском')),
                ('answer_kg', models.TextField(verbose_name='Ответ на кыргызском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'FAQ-TS',
                'verbose_name_plural': 'FAQs-ts',
            },
        ),
        migrations.CreateModel(
            name='FaqModelsVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.TextField(max_length=955, verbose_name='Вопрос на русском')),
                ('question_kg', models.TextField(max_length=955, verbose_name='Вопрос на кыргызском')),
                ('answer_ru', models.TextField(verbose_name='Ответ на русском')),
                ('answer_kg', models.TextField(verbose_name='Ответ на кыргызском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'FAQ-VS',
                'verbose_name_plural': 'FAQs-vs',
            },
        ),
        migrations.DeleteModel(
            name='FaqModels',
        ),
    ]
