# Generated by Django 4.2.4 on 2024-04-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=155, verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='CalculatorEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=155, verbose_name='Двигатель')),
            ],
            options={
                'verbose_name_plural': 'Двигатель',
            },
        ),
        migrations.CreateModel(
            name='CalculatorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=155, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Статус оформления',
            },
        ),
        migrations.CreateModel(
            name='CalculatorVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=155, verbose_name='Объём')),
            ],
            options={
                'verbose_name_plural': 'Объём',
            },
        ),
        migrations.CreateModel(
            name='CalculatorYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=155, verbose_name='Год')),
            ],
            options={
                'verbose_name_plural': 'Год',
            },
        ),
        migrations.CreateModel(
            name='CalculatorAllList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.CharField(max_length=155)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.calculatorcar', verbose_name='Тип')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.calculatorengine', verbose_name='Двигатель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.calculatorstatus', verbose_name='Статус')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.calculatorvolume', verbose_name='Объём')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.calculatoryear', verbose_name='Год')),
            ],
            options={
                'verbose_name_plural': 'Вывод данных калькулятора',
            },
        ),
    ]
