# Generated by Django 4.2.4 on 2024-04-03 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=500, verbose_name='Тема на русском')),
                ('title_ky', models.CharField(max_length=500, verbose_name='Тема на киргизском')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья на русском')),
                ('text_ky', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья на киргизском')),
                ('url_youtube', models.URLField(blank=True, max_length=500, verbose_name='URL с Ютуба')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('viewed', models.IntegerField(default=0, verbose_name='Просмотрено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Путь к фотографиям')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображении',
            },
        ),
    ]
