# Generated by Django 4.2.4 on 2024-04-26 03:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Статья на киргизском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Статья на русском'),
        ),
    ]
