# Generated by Django 4.2.4 on 2024-04-29 03:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url_youtube',
        ),
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='news',
            name='url_youtube_kg',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL с Ютуба на кыргызском'),
        ),
        migrations.AddField(
            model_name='news',
            name='url_youtube_ru',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL с Ютуба на русском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья на кыргызском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=500, verbose_name='Тема на кыргызском'),
        ),
    ]
