# Generated by Django 4.2.4 on 2024-04-26 04:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_text_ky_alter_news_text_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья на киргизском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья на русском'),
        ),
    ]
