# Generated by Django 4.2.4 on 2024-04-26 05:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_text_ky_alter_news_text_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url_youtube',
        ),
        migrations.AddField(
            model_name='news',
            name='url_youtube_kg',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL с Ютуба на кыргызском'),
        ),
        migrations.AddField(
            model_name='news',
            name='url_youtube_ru',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL с Ютуба на русском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья на кыргызском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=500, verbose_name='Тема на кыргызском'),
        ),
    ]
