# Generated by Django 4.2.4 on 2024-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=599, verbose_name='Наименование на русском')),
                ('title_kg', models.CharField(max_length=599, verbose_name='Наименование на кыргызском')),
                ('address_ru', models.TextField(max_length=599, verbose_name='Адрес на русском')),
                ('address_kg', models.TextField(max_length=599, verbose_name='Адрес на кыргызском')),
                ('category', models.TextField(max_length=599, verbose_name='Категория')),
                ('date', models.DateTimeField(verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лизензии',
            },
        ),
    ]
