# Generated by Django 4.2.4 on 2024-05-23 05:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=599, verbose_name='Наименование на русском')),
                ('title_kg', models.CharField(blank=True, max_length=599, verbose_name='Наименование на кыргызском')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья на русском')),
                ('text_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья на кыргызском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Перечень',
                'verbose_name_plural': 'Перечни',
            },
        ),
        migrations.CreateModel(
            name='DocumentsNPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=599, verbose_name='Наименование на русском')),
                ('title_kg', models.CharField(blank=True, max_length=599, verbose_name='Наименование на кыргызском')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья на русском')),
                ('text_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья на кыргызском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'НПА',
                'verbose_name_plural': 'НПА',
            },
        ),
        migrations.CreateModel(
            name='PdfGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Наименование')),
                ('pdf', models.FileField(blank=True, upload_to='pdf/', verbose_name='Вставка файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Форму',
                'verbose_name_plural': 'Форма бланков',
            },
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лизензии для автошкол'},
        ),
        migrations.AddField(
            model_name='license',
            name='issued_authority_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=599, verbose_name='Выданный орган на кыргызском'),
        ),
        migrations.AddField(
            model_name='license',
            name='issued_authority_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=599, verbose_name='Выданный орган на русском'),
        ),
        migrations.AddField(
            model_name='license',
            name='logo',
            field=models.ImageField(blank=True, upload_to='license/logo', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='license',
            name='register_number',
            field=models.CharField(blank=True, max_length=599, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='license',
            name='address_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=599, verbose_name='Адрес на кыргызском'),
        ),
        migrations.AlterField(
            model_name='license',
            name='address_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=599, verbose_name='Адрес на русском'),
        ),
        migrations.AlterField(
            model_name='license',
            name='category',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=599, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='license',
            name='title_kg',
            field=models.CharField(blank=True, max_length=599, verbose_name='Наименование на кыргызском'),
        ),
        migrations.AlterField(
            model_name='license',
            name='title_ru',
            field=models.CharField(blank=True, max_length=599, verbose_name='Наименование на русском'),
        ),
    ]
