# Generated by Django 4.2.4 on 2024-05-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
