# Generated by Django 4.2.4 on 2024-05-30 04:23

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_delete_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Наименование')),
                ('banner', models.ImageField(blank=True, upload_to='banner/', verbose_name='Банер')),
                ('documents_pdf', models.FileField(blank=True, upload_to='pdf/', verbose_name='Вставка файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Формы',
                'verbose_name_plural': 'Формы бланков',
            },
        ),
        migrations.CreateModel(
            name='DopDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=599, verbose_name='Наименование на русском')),
                ('title_kg', models.CharField(blank=True, max_length=599, verbose_name='Наименование на кыргызском')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья на русском')),
                ('text_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Статья на кыргызском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Доп',
                'verbose_name_plural': 'Доп. требований',
            },
        ),
        migrations.CreateModel(
            name='RegionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=599, verbose_name='Регион')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Регионы',
                'verbose_name_plural': 'Регион',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='RatingSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='license/logo', verbose_name='Логотип')),
                ('title_ru', models.CharField(blank=True, max_length=599, verbose_name='Наименование на русском')),
                ('title_kg', models.CharField(blank=True, max_length=599, verbose_name='Наименование на кыргызском')),
                ('percent_true', models.IntegerField(blank=True, max_length=5, verbose_name='Процент прошедших')),
                ('percent_false', models.IntegerField(blank=True, max_length=5, verbose_name='Процент непрошедших')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.regioncategories', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг автошкол',
            },
        ),
    ]
